#Travis Ci Confi

#  Created by Tiago Ferreira on 12/01/2016.
#  Copyright (c) 2016 Tiago Ferreira. All rights reserved.

language: python
python:
  - 3.2
  - 3.3
  - 3.4
  - 3.5
# command to install dependencies

# command to run tests
script: python3
